### ISSUE TITLE
What's the purpose of this lib compared to types-ddd ?

### ISSUE THREAD

**Issue by Toilal** [4lessandrodev/rich-domain#1]
Hi @4lessandrodev and thank you for you repositories for DDD using TypeScript.

I consider DDD for a new project, should I better use this repository (rich-domain) or [4lessandrodev/types-ddd](https://github.com/4lessandrodev/types-ddd) ? It seems rich-domain is a core library from your types-ddd repository, is it right ?

**Comment by 4lessandrodev** [comment]
Hi @Toilal, thank you for appreciating my work.

There are some differences:

- remove third-party dependencies as you can see on issue [115](https://github.com/4lessandrodev/types-ddd/issues/115)
- improve the performance of the toObject method using recursion
- base all iteration of arrays core with iterators
- remove dependency on props having to extend BaseDomainEntity
- create getters and setters automatically to domain components (value object, entity and aggregates)
- implement history to manage state

It would be too complex to deploy this without breaking too much
in the future this lib will be the core of types-ddd in a new version (3.0) with breking changes.
